In [5]:
import numpy as np

In [29]:
arr= np.random.randint(1,100,10)# 1 ile 100 arasında 10 karakterli rastgele dizi oluşturma
arr

array([23, 31, 44, 37, 97, 75, 74, 94, 47, 68])

In [30]:
arr.sort() # diziyi küçükten büyüğe doğru sıralar
arr

array([23, 31, 37, 44, 47, 68, 74, 75, 94, 97])

In [31]:
arr

array([23, 31, 37, 44, 47, 68, 74, 75, 94, 97])

In [32]:
arr5 = arr.copy()
arr5

array([23, 31, 37, 44, 47, 68, 74, 75, 94, 97])

In [33]:
arr5[2] = 18
arr5

array([23, 31, 18, 44, 47, 68, 74, 75, 94, 97])

In [34]:
arr

array([23, 31, 37, 44, 47, 68, 74, 75, 94, 97])

In [8]:
arr2 = arr.copy() # arr dizisini arr2 ye kopyalıyor
arr2[4] = 24 # arr2 dizisinin ilk elemanını 24 yapıyorum
arr2

array([ 5, 13, 28, 38, 24, 42, 75, 90, 93, 94])

In [9]:
arr # arr dizisinde herhangi bir değişiklik yok

array([ 5, 13, 28, 38, 41, 42, 75, 90, 93, 94])

In [10]:
print(arr2.base) # dizi copyalanmışmı yoksa görüntüsümü alınmış tespit etmek için base fonksiyonu kullanılır 
# eğer değer none ise kopyalanmış değilse görüntüsü alınmıştır

None


In [11]:
arr2 = arr.view() # arr dizisini arr2 ye kopyalıyor
arr2[4] = 25 # arr2 dizisinin ilk elemanını 25 yapıyorum
arr2

array([ 5, 13, 28, 38, 25, 42, 75, 90, 93, 94])

In [12]:
arr # arr dizisinde arr2 de yaptığım değişiklikler arr üzerinde uygulanmış oluyor

array([ 5, 13, 28, 38, 25, 42, 75, 90, 93, 94])

In [13]:
print(arr2.base) # dizi copyalanmışmı yoksa görüntüsümü alınmış tespit etmek için base fonksiyonu kullanılır 
# eğer değer none ise kopyalanmış değilse görüntüsü alınmıştır

[ 5 13 28 38 25 42 75 90 93 94]


In [14]:
# 3 boyutlu elemanları rastgele olan 2ye 6lık bir dizi 2 satır 6 sütun
newarr=np.random.randint(1,50,6)

newarr

array([[[21, 20, 49, 46, 15, 31]],

       [[33,  8, 49, 44, 33, 47]]])

In [15]:
newarr.sort() # diziyi küçükten büyüğe doğru sıralar
newarr

array([[[15, 20, 21, 31, 46, 49]],

       [[ 8, 33, 33, 44, 47, 49]]])

In [16]:
newarr.sum(axis=0) # çok boyutlu dizilerde satır ve sütun olayı vardır buradaki sütunların toplamını verir

array([[23, 53, 54, 75, 93, 98]])

In [17]:
newarr = newarr.reshape(4,3)
print(newarr,"\n")

print(newarr.sum(axis=0),"\n") # sütunların toplamı

print(newarr.sum(axis=1),"\n") # satırların toplamı

[[15 20 21]
 [31 46 49]
 [ 8 33 33]
 [44 47 49]] 

[ 98 146 152] 

[ 56 126  74 140] 



In [18]:
newarr.sum(axis=0) # sütunların toplamı

array([ 98, 146, 152])

In [19]:
newarr.sum(axis=1) # satırların toplamı

array([ 56, 126,  74, 140])