In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(-50,50,8)
arr2 = np.random.randint(-50,50,8)
print(arr1,"\n")
print(arr2)

[-26 -50   5 -44 -19  -1 -31  30] 

[-26  -1  32  13 -10 -24  -4 -28]


In [3]:
# numpy ile matematik işlemleri + - * /
print(arr1 + arr2,"\n")
print(arr1 - arr2,"\n")
print(arr1 + 10,"\n")
print(arr1 * arr2,"\n")
print(arr1 * 10,"\n")
print(arr1 / arr2,"\n")
print(arr1 / 10,"\n")



[-52 -51  37 -31 -29 -25 -35   2] 

[  0 -49 -27 -57  -9  23 -27  58] 

[-16 -40  15 -34  -9   9 -21  40] 

[ 676   50  160 -572  190   24  124 -840] 

[-260 -500   50 -440 -190  -10 -310  300] 

[ 1.00000000e+00  5.00000000e+01  1.56250000e-01 -3.38461538e+00
  1.90000000e+00  4.16666667e-02  7.75000000e+00 -1.07142857e+00] 

[-2.6 -5.   0.5 -4.4 -1.9 -0.1 -3.1  3. ] 



In [4]:
# numpy ile ileri matematik işlemleri (cos tan kökalma power üs alma gibi matematiksel işlemler)

print(np.sin(arr1),"\n")
print(np.cos(arr1),"\n")
print(np.abs(arr1),"\n")
print(np.sqrt(np.abs(arr1)),"\n") 
print(np.log(np.abs(arr1)),"\n")
print(np.power(arr1,2),"\n")


[-0.76255845  0.26237485 -0.95892427 -0.01770193 -0.14987721 -0.84147098
  0.40403765 -0.98803162] 

[0.64691932 0.96496603 0.28366219 0.99984331 0.98870462 0.54030231
 0.91474236 0.15425145] 

[26 50  5 44 19  1 31 30] 

[5.09901951 7.07106781 2.23606798 6.63324958 4.35889894 1.
 5.56776436 5.47722558] 

[3.25809654 3.91202301 1.60943791 3.78418963 2.94443898 0.
 3.4339872  3.40119738] 

[ 676 2500   25 1936  361    1  961  900] 



In [16]:
arr1

array([-26, -50,   5, -44, -19,  -1, -31,  30])

In [17]:
np.cos(arr1)

array([0.64691932, 0.96496603, 0.28366219, 0.99984331, 0.98870462,
       0.54030231, 0.91474236, 0.15425145])

In [5]:
print(arr1,"\n")
print(arr2,"\n")
#print("2 diziyi dikey olarak birleştirme işlemi \n",np.concatenate((arr1, arr2),axis=1),"\n")
print("2 diziyi yatay olarak birleştirme işlemi \n",np.concatenate((arr1, arr2)),"\n")
print("2 diziyi dikey olarak birleştirme işlemi \n",np.vstack((arr1,arr2)),"\n")
print("2 diziyi yatay olarak birleştirme işlemi \n",np.hstack((arr1,arr2)))

print("2 diziyi karşılık gelen sütunları ile birleştirme işlemi \n",np.stack((arr1, arr2), axis=1))


[-26 -50   5 -44 -19  -1 -31  30] 

[-26  -1  32  13 -10 -24  -4 -28] 

2 diziyi yatay olarak birleştirme işlemi 
 [-26 -50   5 -44 -19  -1 -31  30 -26  -1  32  13 -10 -24  -4 -28] 

2 diziyi dikey olarak birleştirme işlemi 
 [[-26 -50   5 -44 -19  -1 -31  30]
 [-26  -1  32  13 -10 -24  -4 -28]] 

2 diziyi yatay olarak birleştirme işlemi 
 [-26 -50   5 -44 -19  -1 -31  30 -26  -1  32  13 -10 -24  -4 -28]
2 diziyi karşılık gelen sütunları ile birleştirme işlemi 
 [[-26 -26]
 [-50  -1]
 [  5  32]
 [-44  13]
 [-19 -10]
 [ -1 -24]
 [-31  -4]
 [ 30 -28]]


## 

In [22]:
newarray = np.random.randint(-20,20,15).reshape(3,5)
newarray.sort() # diziyi sıralayı o şekilde bastırdık
newarray

array([[-10,  -2,   4,  11,  13],
       [-14,  -4,  -2,   4,  17],
       [ -3,  -2,   9,  11,  16]])

In [23]:
sonuc = newarray %2 == 0 # dizinin içerisindekilerinin 0 dan büyük olanlarını tespit etme
sonuc

array([[ True,  True,  True, False, False],
       [ True,  True,  True,  True, False],
       [False,  True, False, False,  True]])

In [25]:
newarray[sonuc] # ve 0 dan büyük olan elemanlar

array([-10,  -2,   4, -14,  -4,  -2,   4,  -2,  16])

In [26]:
newarray[newarray % 2 == 0] # dizi içerisinde 2 ye tam bölünenler yani çift olanlar

array([-10,  -2,   4, -14,  -4,  -2,   4,  -2,  16])